runtime: nodejs16 # or another supported version

default_expiration: "1h"
instance_class: B2
basic_scaling:
  max_instances: 3
  idle_timeout: 5m
service: default

entrypoint: node .
service_account: planning-school@driving-monlabo-biz.iam.gserviceaccount.com

build_env_variables:
  BP_NODE_RUN_SCRIPTS: "registry-auth,build" 

env_variables:
  ZIPKIN_ENDPOINT: "https://zipkin-ogzyrk5uzq-ew.a.run.app"
  MONGO_USER: planning
  MONGO_PWD: DB_PASSWORD
  MONGO_HOST: planning-dev.dqieh.mongodb.net
  MONGO_DB: planning-school
  PLANNING_API: "https://planning-api.monlabo.biz/"

handlers:
- url: /public
  static_dir: public

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto