name: Build

# Controls when the action will run. Triggers the workflow on push
# events but only for the main and release-* branch
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (Sonar Cloud)
    runs-on: ubuntu-latest
    environment: 
      name: Dev
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@master
    
    - name: Pull mongo image
      run: docker pull mongo:4.4.10
    
    - name: Pull zipkin image
      run: docker pull openzipkin/zipkin:2.23

    - name: Node install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test-coverage

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - name: Build app
      run : npm run build

    - name: Create docker image
      run: docker build -t europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_REF##*/} .
    
    - name: Setup Gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate to GCR
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Push image to GCR
      run: docker push europe-west1-docker.pkg.dev/driving-monlabo-biz/planning/planning-school:${GITHUB_REF##*/}